apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucketpvc
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  volumeName: bitbucketpv

