apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkin8gbpvc
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeName: jenkin8gbpv


