apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonardemo-pvc
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: sonardemopv


