apiVersion: v1
kind: PersistentVolume
metadata:
   name: sonardemopv
spec:
   capacity:
     storage: 2Gi
   accessModes:
     - ReadWriteMany
     - ReadWriteOnce
   nfs:
     path: /srv/nfs/sonardemopv
     server: master.devops-techm.com
   persistentVolumeReclaimPolicy: Recycle
